package com.ampairs.product.data

import com.ampairs.product.domain.ProductSummary

interface ProductDataService {
    suspend fun getById(uid: String): ProductSummary?
    suspend fun getByIds(ids: List<String>): List<ProductSummary>

    /**
     * Minimal "inline create" used by the order/invoice line editors: persists a new product
     * locally (offline-first, flagged for push) and returns its summary so the caller can add it
     * as a line. [id] must be a UID generated by the calling ViewModel (PRODUCT_PREFIX).
     */
    suspend fun quickCreate(
        id: String,
        name: String,
        code: String,
        sellingPrice: Double,
        mrp: Double,
        taxCode: String,
        baseUnitId: String?,
    ): ProductSummary?
}
