kotlin.code.style=official
#Gradle
org.gradle.jvmargs=-Xmx4048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4048M"
org.gradle.java.home=/Users/omprakashseervi/Library/Java/JavaVirtualMachines/graalvm-jdk-21.0.7/Contents/Home
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Development
org.gradle.configuration-cache=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.apple.xcodeCompatibility.nowarn=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false