package com.ampairs.cbmaintenance.data.repository

import com.ampairs.cbmaintenance.data.db.dao.PmEntryDao
import com.ampairs.cbmaintenance.data.db.entity.toEntity
import com.ampairs.cbmaintenance.data.db.entity.toPmEntry
import com.ampairs.cbmaintenance.domain.model.ChecklistItemResult
import com.ampairs.cbmaintenance.domain.model.PmEntry
import com.ampairs.cbmaintenance.util.CbMaintenanceLogger
import com.ampairs.sync.SyncEntity
import com.ampairs.sync.db.SyncStateDao
import dev.zacsweers.metro.Inject
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

/**
 * Local-only data access for PM entries. Completion / reassignment / assist are offline-first
 * field updates written here (synced = false) and pushed by PmEntrySyncDelegate; the server's
 * bulk-upsert spawns tickets from any failed checklist item (module plan §6). PM entries are
 * generated by the backend scheduled job (every 30 min), not on demand from the app.
 */
@OptIn(ExperimentalTime::class)
@Inject
class PmEntryRepository(
    private val dao: PmEntryDao,
    private val syncStateDao: SyncStateDao,
) {
    fun observeOpenEntries(): Flow<List<PmEntry>> =
        dao.getOpenEntries().map { list -> list.map { it.toPmEntry() } }

    fun observeAllEntries(): Flow<List<PmEntry>> =
        dao.getAllEntries().map { list -> list.map { it.toPmEntry() } }

    /** PM entries created to address a given ticket. */
    fun observeEntriesForTicket(ticketId: String): Flow<List<PmEntry>> =
        dao.getEntriesForTicket(ticketId).map { list -> list.map { it.toPmEntry() } }

    suspend fun getEntry(id: String): PmEntry? = dao.getEntryById(id)?.toPmEntry()

    /**
     * Create an ad-hoc PM task (offline-first). Used to raise maintenance work against a ticket:
     * the entry carries `ticketId`, and when it is completed the server auto-resolves that ticket.
     * The zone is left blank — the server denormalizes it from the store on upsert.
     */
    suspend fun createEntry(entry: PmEntry): Result<PmEntry> = runCatching {
        require(entry.uid.isNotBlank()) { "UID must be set by ViewModel" }
        dao.insertEntry(entry.toEntity().copy(synced = false))
        markPending()
        entry
    }.onFailure { CbMaintenanceLogger.e("PmEntryRepository", "createEntry failed", it) }

    /** Mark a PM done with its checklist results. Failed items spawn tickets server-side on push. */
    suspend fun completeEntry(
        id: String,
        checklistResult: List<ChecklistItemResult>,
        completedByEmployeeId: String? = null,
        assistedByEmployeeIds: List<String>? = null,
    ): Result<Unit> = runCatching {
        val existing = dao.getEntryById(id)?.toPmEntry() ?: return@runCatching Unit
        val updated = existing.copy(
            status = "DONE",
            completedAt = nowIso(),
            completedByEmployeeId = completedByEmployeeId ?: existing.completedByEmployeeId,
            assignedToEmployeeId = existing.assignedToEmployeeId ?: completedByEmployeeId,
            assistedByEmployeeIds = assistedByEmployeeIds?.takeIf { it.isNotEmpty() } ?: existing.assistedByEmployeeIds,
            checklistResult = checklistResult,
        )
        dao.insertEntry(updated.toEntity().copy(synced = false))
        markPending()
        Unit
    }.onFailure { CbMaintenanceLogger.e("PmEntryRepository", "completeEntry failed", it) }

    suspend fun reassignEntry(id: String, newAssigneeId: String): Result<Unit> = runCatching {
        dao.getEntryById(id)?.let {
            dao.insertEntry(it.copy(assignedToEmployeeId = newAssigneeId, synced = false))
            markPending()
        }
        Unit
    }.onFailure { CbMaintenanceLogger.e("PmEntryRepository", "reassignEntry failed", it) }

    private fun nowIso(): String = Clock.System.now().toString()

    private suspend fun markPending() =
        syncStateDao.markPendingPush(SyncEntity.CB_PM_ENTRY, Clock.System.now().toEpochMilliseconds())
}
