package com.ampairs.purchase.db

import com.ampairs.purchase.db.dao.PurchaseDao
import com.ampairs.purchase.db.entity.PurchaseEntity
import com.ampairs.purchase.db.entity.PurchaseItemEntity
import com.ampairs.sync.SyncEntity
import com.ampairs.sync.db.SyncStateDao
import dev.zacsweers.metro.Inject
import kotlinx.coroutines.flow.Flow
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

/**
 * Local-only purchase repository (offline-first). Writes go to Room and flag the entity
 * PENDING_PUSH; [com.ampairs.purchase.sync.PurchaseSyncDelegate] owns ALL purchase ↔ server traffic.
 * The repository never injects or calls [com.ampairs.purchase.api.PurchaseApi].
 */
@OptIn(ExperimentalTime::class)
@Inject
class PurchaseRepository(
    private val purchaseDao: PurchaseDao,
    private val syncStateDao: SyncStateDao,
) {

    fun getAllPurchases(): Flow<List<PurchaseEntity>> = purchaseDao.getAllPurchases()

    fun observePurchaseById(purchaseId: String): Flow<PurchaseEntity?> =
        purchaseDao.observePurchaseById(purchaseId)

    fun observePurchaseItems(purchaseId: String): Flow<List<PurchaseItemEntity>> =
        purchaseDao.observePurchaseItems(purchaseId)

    suspend fun getPurchase(id: String): PurchaseEntity? = purchaseDao.selectById(id)

    suspend fun getPurchaseItems(purchaseId: String): List<PurchaseItemEntity> =
        purchaseDao.getPurchaseItems(purchaseId)

    /**
     * Create/update a purchase with its line items, atomically. The UID is generated by the
     * ViewModel (PUR prefix); the number is client-assigned at save from a local counter when blank.
     * Writes are flagged unsynced + PENDING_PUSH so CentralSyncService pushes them automatically.
     */
    suspend fun savePurchase(purchase: PurchaseEntity, items: List<PurchaseItemEntity>): Result<PurchaseEntity> {
        require(purchase.id.isNotBlank()) { "UID must be set by the ViewModel" }
        val numbered =
            if (purchase.purchase_number.isBlank()) purchase.copy(purchase_number = assignNumber())
            else purchase
        val parent = numbered.copy(synced = 0)
        val itemRows = items.map { it.copy(purchase_id = parent.id) }
        purchaseDao.savePurchaseWithItems(parent, itemRows)
        markPending()
        return Result.success(parent)
    }

    /** Soft-delete: active=false, synced=false so the push (reads synced=0) sends the deletion. */
    suspend fun deletePurchase(id: String): Result<Unit> {
        val existing = purchaseDao.selectById(id) ?: return Result.success(Unit)
        purchaseDao.insertPurchase(existing.copy(active = 0, soft_deleted = 1, synced = 0))
        markPending()
        return Result.success(Unit)
    }

    /** Next number this device would assign at save — shown in the editor header. */
    suspend fun nextNumberPreview(): String = assignNumber()

    private suspend fun assignNumber(): String {
        val seq = (purchaseDao.maxPurchaseSequence() ?: 0L) + 1L
        return "PUR-" + seq.toString().padStart(4, '0')
    }

    private suspend fun markPending() =
        syncStateDao.markPendingPush(SyncEntity.PURCHASE, Clock.System.now().toEpochMilliseconds())
}
