package com.ampairs.agent.data.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.ampairs.agent.data.db.dao.AiModelDao
import com.ampairs.agent.data.db.entity.AiModelEntity

/**
 * **App-scoped** Room database for the on-device model catalog (the backend manifest). One global DB
 * file (`agent_catalog.db`), built directly per platform like `AuthRoomDatabase` — NOT the
 * workspace-scoped [ChatDatabase] — because the model files are global (a single app-wide models dir)
 * and the same catalog applies to every workspace. Persisting it makes already-downloaded models
 * selectable + loadable offline. Version 1.
 */
@Database(
    entities = [AiModelEntity::class],
    version = 1,
    exportSchema = true,
)
@ConstructedBy(AgentCatalogDatabaseConstructor::class)
abstract class AgentCatalogDatabase : RoomDatabase() {
    abstract fun aiModelDao(): AiModelDao
}

/** Platform-specific constructor; the actual is generated by the Room KSP compiler per target. */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AgentCatalogDatabaseConstructor : RoomDatabaseConstructor<AgentCatalogDatabase> {
    override fun initialize(): AgentCatalogDatabase
}
