package com.ampairs.agent.data.db

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import com.ampairs.agent.data.db.dao.ChatMessageDao
import com.ampairs.agent.data.db.entity.ChatMessageEntity

/**
 * Workspace-isolated Room database for the assistant chat transcript (resume-on-reopen). One DB file
 * per workspace via [com.ampairs.common.database.WorkspaceAwareDatabaseFactory], so no workspace
 * column is needed. Version 1.
 */
@Database(
    entities = [ChatMessageEntity::class],
    version = 1,
    exportSchema = true,
)
@ConstructedBy(ChatDatabaseConstructor::class)
abstract class ChatDatabase : RoomDatabase() {
    abstract fun chatMessageDao(): ChatMessageDao
}

/** Platform-specific constructor; the actual is generated by the Room KSP compiler per target. */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object ChatDatabaseConstructor : RoomDatabaseConstructor<ChatDatabase> {
    override fun initialize(): ChatDatabase
}
