package com.ampairs.agent.voice

import kotlinx.coroutines.flow.StateFlow

/**
 * Records and replays in-chat voice notes via kodio. This is a **voice-notes-only** feature — it does
 * NOT transcribe and is independent of the [com.ampairs.agent.speech] STT/TTS pipeline. The audio is
 * held in memory keyed by note id (chat is ephemeral, so no file/DB persistence is needed).
 *
 * Platform bindings (`@ContributesTo(AppScope)` + `@Provides @SingleIn(AppScope)`): Android sets the
 * kodio application context before constructing the impl; Desktop/iOS construct it directly. The
 * `RECORD_AUDIO` runtime gate is handled by [com.ampairs.agent.permission.MicPermissionController]
 * before [startRecording] (so kodio's own permission check sees `Granted`).
 */
interface VoiceNoteController {

    /** Whether a recording is currently in progress. */
    val recordingState: StateFlow<VoiceRecordingState>

    /** Id of the note currently playing, or null when idle. */
    val playingNoteId: StateFlow<String?>

    /** Begin capturing from the microphone. Mic permission must already be granted. */
    suspend fun startRecording()

    /**
     * Stop capture and retain the result under [noteId] (generated by the ViewModel, per the
     * UID-in-ViewModel rule). Returns the note handle, or null if nothing usable was captured.
     */
    suspend fun stopRecording(noteId: String): VoiceNote?

    /** Abort an in-progress recording, discarding any captured audio. */
    fun cancelRecording()

    /** Play the note stored under [noteId]; no-op if unknown. Updates [playingNoteId]. */
    fun play(noteId: String)

    /** Stop any in-progress playback. */
    fun stopPlayback()
}
